### ISSUE TITLE
investigate failing CI

### ISSUE THREAD

**Issue by efiop** [fsspec/ossfs#58]
https://github.com/fsspec/ossfs/actions/runs/1473858258

**Comment by karajan1001** [comment]
It was because the storage auto-archive, need to automatically refresh the data in the storage system before CI.

**Comment by efiop** [comment]
@karajan1001 Can we turn off auto-archive in oss settings?

**Comment by karajan1001** [comment]
> @karajan1001 Can we turn off auto-archive in oss settings?
The problem is that we want the OSS bucket to clean up test folders, and for this reason, I made the auto-clean rule for the bucket, And seems that OSS didn't provide a exclude for the bucket level of rule. So, I guess we need to first collect these test folders into some directories and then make the auto-clean rule only affect things inside it.

**Comment by efiop** [comment]
@karajan1001 Do you mean that there are some files that we rely on to be persistent for our tests? If so, why can't we just create them in the test suit like we do in s3/gs/etc tests in dvc?

**Comment by karajan1001** [comment]
> It was because of the storage auto-archive, I had updated the data type in the loss bucket, and it passed. One solution is to automatically refresh the data in the storage system before CI.
>> One solution is to automatically refresh the data in the storage system before CI.

Yes that is what I mean in "automatically refresh"
